using System;
using System.Collections.Generic;
using System.Text;

namespace L2_login
{
    enum PServer : byte
    {
        Die = 0x00,
        Revive = 0x01,
        AttackOutOfRange = 0x02,
        AttackInCoolTime = 0x03,
        AttackDeadTarget = 0x04,
        SpawnItem = 0x05,
        SellList = 0x06,
        BuyList = 0x07,
        DeleteObject = 0x08,
        CharacterSelectionInfo = 0x09,
        LoginFail = 0x0A,
        CharSelected = 0x0B, //GD OK
        NpcInfo = 0x0C,
        NewCharacterSuccess = 0x0D,
        NewCharacterFail = 0x0E,
        CharacterCreateSuccess = 0x0F,

        CharacterCreateFailed = 0x10,
        ItemList = 0x11,
        SunRise = 0x12,
        SunSet = 0x13,
        TradeStart = 0x14,
        TradeStartOk = 0x15,
        DropItem = 0x16,
        GetItem = 0x17,
        StatusUpdate = 0x18,
        NpcHtmlMessage = 0x19,
        TradeOwnAdd = 0x1A,
        TradeOtherAdd = 0x1B,
        TradeDone = 0x1C,
        CharacterDeleteSuccess = 0x1D,
        CharacterDeleteFail = 0x1E,
        ActionFailed = 0x1F,

        ServerClose = 0x20,
        InventoryUpdate = 0x21,
        TeleportToLocation = 0x22,
        TargetSelected = 0x23,
        TargetUnselected = 0x24,
        AutoAttackStart = 0x25,
        AutoAttackStop = 0x26,
        SocialAction = 0x27,
        ChangeMoveType = 0x28,
        ChangeWaitType = 0x29,
        ManagePledgePower = 0x2A,
        CreatePledge = 0x2B,
        AskJoinPledge = 0x2C,
        JoinPledge = 0x2D,
        VersionCheck = 0x2E, //KeyPacket
        MTL = 0x2F,

        NS = 0x30,
        CI = 0x31,
        UI = 0x32, //GD OK
        Attack = 0x33,
        WithdrawalPledge = 0x34,
        OustPledgeMember = 0x35,
        SetOustPledgeMember = 0x36,
        DismissPledge = 0x37,
        SetDismissPledge = 0x38,
        AskJoinParty = 0x39,
        JoinParty = 0x3A,
        WithdrawalParty = 0x3B,
        OustPartyMember = 0x3C,
        SetOustPartyMember = 0x3D,
        DismissParty = 0x3E,
        SetDismissParty = 0x3F,

        MagicAndSkillList = 0x40,
        WareHouseDepositList = 0x41,
        WareHouseWithdrawalList = 0x42,
        WareHouseDone = 0x43,
        ShortCutRegister = 0x44,
        ShortCutInit = 0x45,
        ShortCutDelete = 0x46,
        StopMove = 0x47,
        MagicSkillUser = 0x48,
        MagicSkillCancelId = 0x49,
        CreatureSay = 0x4A,
        EquipUpdate = 0x4B,
        DoorInfo = 0x4C,
        DoorStatusUpdate = 0x4D,
        PartySmallWindowAll = 0x4E,
        PartySmallWindowAdd = 0x4F,

        PartySmallWindowDeleteAll = 0x50,
        PartySmallWindowDelete = 0x51,
        PartySmallWindowUpdate = 0x52,
        TradePressOwnOk = 0x53,
        MagicSkillLaunched = 0x54,
        FriendAddRequestResult = 0x55,
        FriendAdd = 0x56,
        FriendRemove = 0x57,
        FriendList = 0x58,
        FriendStatus = 0x59,
        PledgeShowMemberListAll = 0x5A,
        PledgeShowMemberListUpdate = 0x5B,
        PledgeShowMemberListAdd = 0x5C,
        PledgeShowMemberListDelete = 0x5D,
        MagicList = 0x5E,
        SkillList = 0x5F,

        VehicleInfo = 0x60,
        FinishRotating = 0x61,
        SystemMessage = 0x62,
        StartPledgeWar = 0x63,
        ReplyStartPledgeWar = 0x64,
        StopPledgeWar = 0x65,
        ReplyStopPledgeWar = 0x66,
        SurrenderPledgeWar = 0x67,
        ReplySurrenderPledgeWar = 0x68,
        SetPledgeCrest = 0x69,
        PledgeCrest = 0x6A,
        SetupGauge = 0x6B,
        VehicleDeparture = 0x6C,
        VehicleCheckLocation = 0x6D,
        GetOnVehicle = 0x6E,
        GetOffVehicle = 0x6F,

        TradeRequest = 0x70,
        RestartResponse = 0x71,
        MoveToPawn = 0x72,
        SSQInfo = 0x73,
        GameGuardQuery = 0x74,
        L2FriendList = 0x75,
        L2Friend = 0x76,
        L2FriendStatus = 0x77,
        L2FriendSay = 0x78,
        ValidateLocation = 0x79,
        StartRotating = 0x7A,
        ShowBoard = 0x7B,
        ChooseInventoryItem = 0x7C,
        Dummy1 = 0x7D,
        MoveToLocationInVehicle = 0x7E,
        StopMoveInVehicle = 0x7F,

        ValidateLocationInVehicle = 0x80,
        TradeUpdate = 0x81,
        TradePressOtherOk = 0x82,
        FriendAddRequest = 0x83,
        LogOutOk = 0x84,
        AbnormalStatusUpdate = 0x85,
        QuestList = 0x86,
        EnchantResult = 0x87,
        PledgeShowMemberListDeleteAll = 0x88,
        PledgeInfo = 0x89,
        PledgeExtendedInfo = 0x8A,
        SurrenderPersonally = 0x8B,
        Ride = 0x8C,
        Dummy2 = 0x8D,
        PledgeShowInfoUpdate = 0x8E,
        ClientAction = 0x8F,

        AcquireSkillList = 0x90,
        AcquireSkillInfo = 0x91,
        ServerObjectInfo = 0x92,
        GMHide = 0x93,
        AcquireSkillDon = 0x94,
        GMViewCharacterInfo = 0x95,
        GMViewPledgeInfo = 0x96,
        GMViewSkillInfo = 0x97,
        GMViewMagicInfo = 0x98,
        GMViewQuestList = 0x99,
        GMViewItemList = 0x9A,
        GmViewWarehouseWithdrawList = 0x9B,
        ListPartyWaiting = 0x9C,
        PartyRoomInfo = 0x9D,
        PlaySound = 0x9E,
        StaticObject = 0x9F,

        PrivateStoreManageListSell = 0xA0,
        PrivateStoreListSell = 0xA1,
        PrivateStoreMsgSell = 0xA2,
        ShowMiniMap = 0xA3,
        ReviveRequest = 0xA4,
        AbnormalVisualEffect = 0xA5,
        TutorialShowHtml = 0xA6,
        TutorialShowQuestionMark = 0xA7,
        TutorialEnableClientEvent = 0xA8,
        TutorialShowHtmlCloseWindow = 0xA9,
        ShowRadar = 0xAA,
        WithdrawAlliance = 0xAB,
        OustAllianceMemberPledge = 0xAC,
        DismissAlliance = 0xAD,
        SetAllianceCrest = 0xAE,
        AllianceCrest = 0xAF,

        ServerCloseSocket = 0xB0,
        PetStatusShow = 0xB1,
        PetInfo = 0xB2,
        PetItemList = 0xB3,
        PetInventoryUpdate = 0xB4,
        AllianceInfo = 0xB5,
        PetStatusUpdate = 0xB6,
        PetDelete = 0xB7,
        DeleteRadar = 0xB8,
        MyTargetSelected = 0xB9,
        PartyMemberPosition = 0xBA,
        AskJoinAlly = 0xBB,
        JoinAlliance = 0xBC,
        PrivateStoreBuyManageList = 0xBD,
        PrivateStoreBuyList = 0xBE,
        PrivateStoreBuyMsg = 0xBF,

        VehicleStart = 0xC0,
        RequestTimeCheck = 0xC1,
        StartAllianceWar = 0xC2,
        ReplyStartAllianceWar = 0xC3,
        StopAllianceWar = 0xC4,
        ReplyStopAllianceWar = 0xC5,
        SurrenderAllianceWar = 0xC6,
        SkillCoolTime = 0xC7,
        PackageToList = 0xC8,
        CastleSiegeInfo = 0xC9,
        CastleSiegeAttackerList = 0xCA,
        CastleSiegeDefenderList = 0xCB,
        NickNameChanged = 0xCC,
        PledgeStatusChanged = 0xCD,
        RelationChanged = 0xCE,
        EventTrigger = 0xCF,

        MultiSellList = 0xD0,
        SetSummonRemainTime = 0xD1,
        PackageSendableList = 0xD2,
        Earthquake = 0xD3,
        FlyToLocation = 0xD4,
        BlockList = 0xD5,
        SpecialCamera = 0xD6,
        NormalCamera = 0xD7,
        SkillRemainSec = 0xD8,
        NetPing = 0xD9,
        Dice = 0xDA,
        Snoop = 0xDB,
        RecipeBookItemList = 0xDC,
        RecipeItemMakeInfo = 0xDD,
        RecipeShopManageList = 0xDE,
        RecipeShopSellList = 0xDF,

        RecipeShopItemInfo = 0xE0,
        RecipeShopMsg = 0xE1,
        ShowCalc = 0xE2,
        MonRaceInfo = 0xE3,
        HennaItemInfo = 0xE4,
        HennaInfo = 0xE5,
        HennaUnequipList = 0xE6,
        HennaUnequipInfo = 0xE7,
        MacroList = 0xE8,
        BuyListSeed = 0xE9,
        ShowTownMap = 0xEA,
        ObservationMode = 0xEB,
        ObservationReturn = 0xEC,
        CharSit = 0xED,
        HennaEquipList = 0xEE,
        SellListProcure = 0xEF,

        GMHennaInfo = 0xF0,
        RadarControl = 0xF1,
        ClientSetTime = 0xF2,
        ConfirmDlg = 0xF3,
        PartySpelled = 0xF4,
        ShopPreviewList = 0xF5,
        ShopPreviewInfo = 0xF6,
        CameraMode = 0xF7,
        ShowXMasSeal = 0xF8,
        EtcStatusUpdate = 0xF9,
        ShortBuffStatusUpdate = 0xFA,
        SSQStatus = 0xFB,
        PetitionVote = 0xFC,
        AgitDecoInfo = 0xFD,
        EXPacket = 0xFE,
        EXDummy = 0xFF
    }
    
    enum PServerEX : uint
    {
        ExDummy = 0x00,
        ExSecurityPinCorrect = 0x10B,
        ExShowSecurityPinWindow = 0x10A,
        ExUserinfoStats = 0x015F,
        ExUserInfo = 0x0160,
        ExUserinfoItems = 0x0161,
        ExNpcInfo = 0x0167,
        ExMailArrived = 0x2E,
        ExSetCompassZoneCode = 0x33,
        ExShowScreenMessage = 0x3900,
        ExQuestHTML = 0x8D,
        ExShowReceivedPostList = 0xAA,
        ExVitalityUpdate = 0xA0,
        ExQuestItemList = 0xC5,
        ExBrExtraUserInfo = 0xCF,
        ExAcquireSkillInfo = 0xFB,
        ExtargetBuffs = 0xE6,
        ExPartyPetWindowAdd = 0x18,
        ExPartyPetWindowDelete = 0x6a,
        ExSendUIEventPacket = 0x8E,
        ExNewSkillToLearnByLevelup = 0xFC
        
    }
    
    enum PClient : byte
    {
        Logout = 0x00,
        AttackRequest = 0x01,
        RequestStartPledgeWar = 0x03,
        RequestReplyStartPledgeWar = 0x04,
        RequestStopPledgeWar = 0x05,
        RequestReplyStopPledgeWar = 0x06,
        RequestSurrenderPledgeWar = 0x07,
        RequestReplySurrenderPledgeWar = 0x08,
        RequestSetPledgeCrest = 0x09,
        RequestGiveNickName = 0x0B,
        CharacterCreate = 0x0C,
        CharacterDelete = 0x0D,
        AuthLogin = 0x0E, //ProtocolVersion
        MoveBackwardToLocation = 0x0F, //GD OK

        EnterWorld = 0x11,
        CharacterSelect = 0x12,
        NewCharacter = 0x13,
        RequestItemList = 0x14,
        RequestUnEquipItem = 0x16, //*
        RequestDropItem = 0x17,
        UseItem = 0x19, //GD OK
        TradeRequest = 0x1A,
        AddTradeItem = 0x1B,
        TradeDone = 0x1C,
        Action = 0x1F, //GD OK

        RequestLinkHtml = 0x22,
        RequestBypassToServer = 0x23,
        RequestBBSwrite = 0x24,
        RequestJoinPledge = 0x26,
        RequestAnswerJoinPledge = 0x27,
        RequestWithdrawalPledge = 0x28,
        RequestOustPledgeMember = 0x29,
        RequestPlayerList = 0x2B, //AuthLogin
        RequestGetItemFromPet = 0x2C,
        RequestAllyInfo = 0x2E,
        RequestCrystallizeItem = 0x2F,
        RequestPrivateStoreManageSell = 0x30,
        SetPrivateStoreListSell = 0x31,
        RequestPrivateStoreManageCancel = 0x32, //*
        RequestSocialAction = 0x34,
        ChangeMoveType2 = 0x35,
        ChangeWaitType2 = 0x36,
        RequestSellItem = 0x37,
        RequestMagicSkillList = 0x38,
        RequestMagicSkillUse = 0x39,
        Appearing = 0x3A, //GD OK
        SendWareHouseDepositList = 0x3B,
        SendWareHouseWithDrawList = 0x3C,
        RequestShortCutReg = 0x3D,
        RequestShortCutDel = 0x3F,

        RequestBuyItem = 0x40,
        RequestJoinParty = 0x42,
        RequestAnswerJoinParty = 0x43,
        RequestWithDrawalParty = 0x44,
        RequestOustPartyMember = 0x45,
        RequestDismissParty = 0x46, //*
        CannotMoveAnymore = 0x47,
        RequestTargetCanceled = 0x48,
        Say2 = 0x49,
        RequestPledgeMemberList = 0x4D,
        DummyPacket = 0x4F,

        RequestSkillList = 0x50, //followed by A6 ... dunno why?
        MoveWithDelta = 0x52,
        RequestGetOnVehicle = 0x53,
        RequestGetOffVehicle = 0x54,
        RequestAnswerTrade = 0x55, //RequestGetOnVehicle
        RequestActionUse = 0x56,
        RequestRestart = 0x57,
        RequestSiegeInfo = 0x58,
        ValidatePosition = 0x59, //GD Heading wrong?
        RequestSEKCustom = 0x5A,
        StartRotating = 0x5B,
        FinishRotating = 0x5C,
        RequestShowBoard = 0x5E,
        RequestEnchantItem = 0x5F,

        RequestDestroyItem = 0x60,
        RequestQuestList = 0x62,
        RequestQuestAbort = 0x63,
        RequestPledgeInfo = 0x65,
        RequestPledgeCrest = 0x67,
        RequestSendFriendMsg = 0x6B,
        RequestShowMiniMap = 0x6C,
        MSNDialog = 0x6D,
        RequestRecordInfo = 0x6E,
        RequestHennaEquip = 0x6F,

        RequestAquireSkillInfo = 0x73,
        SendBypassBuildCmd = 0x74,
        RequestMoveToLocationInVehicle = 0x75,
        CannotMoveAnymoreInVehicle = 0x76,
        RequestFriendInvite = 0x77,
        RequestAnswerFriendInvite = 0x78,
        RequestFriendList = 0x79,
        RequestFriendDel = 0x7A,
        CharacterRestore = 0x7B,
        RequestAquireSkill = 0x7C,
        RequestRestartPoint = 0x7D,
        RequestGMCommand = 0x7E,
        RequestPartyMatchConfig = 0x7F,

        RequestPartyMatchList = 0x80,
        RequestPartyMatchDetail = 0x81,
        RequestPrivateStoreList = 0x82, //*
        RequestPrivateStoreBuy = 0x83,
        RequestTutorialLinkHtml = 0x85,
        RequestTutorialPassCmdToServer = 0x86,
        RequestTutorialQuestionMark = 0x87,
        RequestTutorialClientEvent = 0x88,
        RequestPetition = 0x89,
        RequestPetitionCancel = 0x8A,
        RequestGmList = 0x8B,
        RequestJoinAlly = 0x8C,
        RequestAnswerJoinAlly = 0x8D,
        AllyLeave = 0x8E,
        AllyDismiss = 0x8F,

        RequestDismissAlly = 0x90,
        RequestSetAllyCrest = 0x91,
        RequestAllyCrest = 0x92,
        RequestChangePetName = 0x93,
        RequestPetUseItem = 0x94,
        RequestGiveItemToPet = 0x95,
        RequestPrivateStoreQuitSell = 0x96,
        SetPrivateStoreMsgSell = 0x97,
        RequestPetGetItem = 0x98,
        RequestPrivateStoreManageBuy = 0x99,
        SetPrivateStoreListBuy  = 0x9A,
        RequestPrivateStoreBuyManageCancel = 0x9B, //*
        RequestPrivateStoreQuitBuy = 0x9C,
        SetPrivateStoreMsgBuy = 0x9D,
        RequestPrivateStoreBuyList = 0x9E, //*
        RequestPrivateStoreSell = 0x9F,

        RequestSkillCoolTime = 0xA6, //GD OK
        RequestPackageSendableItemList = 0xA7,
        RequestPackageSend = 0xA8,
        RequestBlock = 0xA9,
        RequestCastleSiegeInfo = 0xAA,
        RequestSiegeAttackerList = 0xAB,
        RequestSiegeDefenderList = 0xAC,
        RequestJoinSiege = 0xAD,
        RequestConfirmSiegeWaitingList = 0xAE,
        RequestSetCastleSiegeTime = 0xAF, //*

        MultiSellChoose = 0xB0,
        NetPingReply = 0xB1,
        RequestUserCommand = 0xB3,
        SnoopQuit = 0xB4,
        RequestRecipeBookOpen = 0xB5,
        RequestRecipeBookDestroy = 0xB6,
        RequestRecipeItemMakeInfo = 0xB7,
        RequestRecipeItemMakeSelf = 0xB8,
        RequestRecipeShopManageList = 0xB9, //*
        RequestRecipeShopMessageSet = 0xBA,
        RequestRecipeShopListSet = 0xBB,
        RequestRecipeShopManageQuit = 0xBC,
        RequestRecipeShopMakeInfo = 0xBE,
        RequestRecipeShopMakeItem = 0xBF,

        RequestRecipeShopManagePrev = 0xC0,
        ObserverReturn = 0xC1,
        RequestEvaluate = 0xC2,
        RequestHennaList = 0xC3,
        RequestHennaItemInfo = 0xC4,
        RequestBuySeed = 0xC5,
        DlgAnswer = 0xC6,
        RequestWearItem = 0xC7,
        RequestSSQStatus = 0xC8,
        GameGuardReply = 0xCB,
        RequestPledgePower = 0xCC,
        RequestMakeMacro = 0xCD,
        RequestDeleteMacro = 0xCE,
        RequestBuyProcure = 0xCF,

        EXPacket = 0xD0,
    }

    enum PClientCmd : byte
    {
        Loc = 0x00,
        Stuck = 0x34,
        Mount = 0x3D,
        Dismount = 0x3E,
        Time = 0x4D,
        PartyInfo = 0x51,
        AttackList = 0x58,
        WarList = 0x5A,
        SiegeStatus = 0x63,
        ClanPenalty = 0x64,
        InstanceZone = 0x72,
        MyBirthday = 0x7E
    }

    enum PClientEX : byte
    {
        RequestManorList = 0x01,
        RequestProcureCropList = 0x02,
        RequestSetSeed = 0x03,
        RequestSetCrop = 0x04,
        RequestWriteHeroWords = 0x05,
        RequestExAskJoinMPCC = 0x06,
        RequestExAcceptJoinMPCC = 0x07,
        RequestExOustFromMPCC = 0x08,
        RequestOustFromPartyRoom = 0x09,
        RequestDismissPartyRoom = 0x0A,
        RequestWithdrawPartyRoom = 0x0B,
        RequestChangePartyLeader = 0x0C,
        //RequestAutoSoulShot = 0x0D,
        RequestExEnchantSkillInfo = 0x0E,
        RequestExEnchantSkill = 0x0F,

        RequestExPledgeCrestLarge = 0x10,
        RequestExSetPledgeCrestLarge = 0x11,
        RequestPledgeSetAcademyMaster = 0x12,
        RequestPledgePowerGradeList = 0x13,
        RequestPledgeMemberPowerInfo = 0x14,
        RequestPledgeSetMemberPowerGrade = 0x15,
        RequestPledgeMemberInfo = 0x16,
        RequestPledgeWarList = 0x17,
        RequestExFishRanking = 0x18,
        RequestPCCafeCouponUse = 0x19,
        SomethingLong1 = 0x1A,
        RequestDuelStart = 0x1B,
        RequestDuelAnswerStart = 0x1C,
        RequestExRqItemLink = 0x1E,

        RequestKeyMapping = 0x21,
        RequestExRemoveItemAttribute = 0x23,
        RequestSaveInventoryOrder = 0x24,
        RequestExitPartyMatchingWaitingRoom = 0x25,
        RequestConfirmTargetItem = 0x26,
        RequestConfirmRefinerItem = 0x27,
        RequestConfirmGemStone = 0x28,
        RequestOlympiadObserverEnd = 0x29,
        RequestCursedWeaponList = 0x2A,
        RequestCursedWeaponLocation = 0x2B,
        RequestPledgeReorganizeMember = 0x2C,
        RequestExMPCCShowPartyMembersInfo = 0x2E,
        RequestOlympiadMatchList = 0x2F,

        RequestAskJoinPartyRoom = 0x30,
        AnswerJoinPartyRoom = 0x31,
        RequestListPartyMatchingWaitingRoom = 0x32,
        RequestExEnchantSkillSafe = 0x33,
        RequestExEnchantSkillUntrain = 0x34,
        RequestExEnchantSkillRouteChange = 0x35,
        ExGetOnAirShip = 0x36,
        ExGetOffAirShip = 0x37, //*
        RequestExEnchantItemAttribute = 0x38,
        CreateCharConfirm = 0x39,
        RequestAllFortressInfo = 0x3D,
        RequestAllCastleInfo = 0x3F,

        //RequestAllFortressInfo = 0x40,
        RequestAllAgitInfo = 0x41,
        RequestFortressSiegeInfo = 0x42,
        RequestGetBossRecord = 0x43,
        RequestRefine = 0x44,
        RequestConfirmCancelItem = 0x45,
        RequestRefineCancel = 0x46,
        RequestExMagicSkillUseGround = 0x47,
        RequestDuelSurrender = 0x48,
        RequestExEnchantSkillInfoDetail = 0x49,        
        RequestFortressMapInfo = 0x48, // Freya
        SetPrivateStoreWholeMsg = 0x4D,
        RequestDispel = 0x4B, // Freya
        RequestExTryToPutEnchantTargetItem = 0x4F,

        RequestExTryToPutEnchantSupportItem = 0x50,
        RequestExCancelEnchantItem = 0x51,
        RequestChangeNicknameColor = 0x52,
        RequestResetNickname = 0x53,
        RequestEvaluate = 0x7E,
        RequestSecurityPinWindow = 0xAD,
        SecurityPin = 0xAB,

        Login3 = 0xB6,
        Login2 = 0x64,
        Login1 = 0x66,

        Login4 = 0xCE,

        RequestAutoSoulShot = 0xDD, //GD OK
        RequestCrystallizeEstimate = 0x91,
        RequestCrystallizeCancel = 0x92

    }

    enum PClientAction : byte
    {
        SitStand = 0,
        RunWalk = 1,
        Attack = 2,
        Trade = 3,
        NextTarget = 4,
        PickUp = 5,
        Assist = 6,
        Invite = 7,
        LeaveParty = 8,
        DismissPartyMember = 9,
        Open_PrivateStore_Sell = 10,
        PartyMatching = 11,
        Social_Greeting = 12,
        Social_Victory = 13,
        Social_Advance = 14,
        Pet_RunWalk = 15,
        Pet_Attack = 16,
        Pet_Stop = 17,
        Pet_PickUp = 18,
        Pet_Unsummon = 19,
        Pet_Special = 20,
        Summon_RunWalk = 21,
        Summon_Attack = 22,
        Summon_Stop = 23,
        Social_Yes = 24,
        Social_No = 25,
        Social_Bow = 26,
        Summon_Special = 27,
        Open_PrivateStore_Buy = 28,
        Social_Unaware = 29,
        Social_Waiting = 30,
        Social_Laugh = 31,
        SwitchMode = 32,
        Social_Applaud = 33,
        Social_Dance = 34,
        Social_Sorrow = 35,
        ToxicSmoke = 36,
        Open_DwarvenManufacture = 37,
        Mount = 38,
        ParasiteBurst = 39,
        Evaluate = 40,
        WildCannon = 41,
        SelfDamageShield = 42,
        HydroScrew = 43,
        BoomAttack = 44,
        MasterRecharge = 45,
        MegaStormStrike = 46,
        StealBlood = 47,
        MechCannon = 48,
        WildTemper = 49,
        ChangePartyLeader = 50,
        Open_GeneralManufacture = 51,
        Summon_Unsummon = 52,
        Summon_Move = 53,
        Pet_Move = 54,
        Record = 55,
        CommandChannelInvite = 56,
        FindStore = 57,
        Duel = 58,
        Withdraw = 59,
        PartyDuel = 60,
        Open_PackageSale = 61,
        Social_Charm = 62,
        MiniGame = 63,
        MyTeleports = 64,
        BotReport = 65,
        Social_Shyness = 66,
        Steer = 67,
        CancelControl = 68,
        DestinationMap = 69,
        ExitAirship = 70,
    }
}
